AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
Naming/VariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false